// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Student struct {
	ID          in     `json:"id"`
	Name        string `json:"name"`
	Npm         int    `json:"npm"`
	BidangStudi string `json:"bidangStudi"`
	Fakultas    string `json:"fakultas"`
}

type StudentInput struct {
	Name        string `json:"name"`
	Npm         int    `json:"npm"`
	BidangStudi string `json:"bidangStudi"`
	Fakultas    string `json:"fakultas"`
}
